name: floating_overlay
description: A widget wrapper that allows a floating widget be dragged and rescaled.
version: 1.2.1
homepage: https://github.com/FMorschel/floating_overlay
repository: https://github.com/FMorschel/floating_overlay
issue_tracker: https://github.com/FMorschel/floating_overlay/issues

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  logging: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter: null
